Finetune a model that uses the output to predict the instruction

In [ ]:
print("** Finetune model that uses output to predict the instruction **")
#1. SETUP - Install and Imports
!pip uninstall -y cudf-cu12 pylibcudf-cu12 dask-cudf-cu12 cuml-cu12
!pip install -q -U transformers datasets accelerate bitsandbytes "numpy==2.0.0" "pyarrow>=15.0.2" peft

import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)
from huggingface_hub import login
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

#2. CONFIGURATION - Set key variables
IS_GPU_ENV = True
CPU_MODEL_ID = "distilgpt2"
GPU_MODEL_ID = "meta-llama/Llama-2-7b-hf"
DATASET_ID = "timdettmers/openassistant-guanaco"
HF_REPO_ID = "dnerkar/llama-2-7b-backward-lora"

#3. AUTHENTICATION - Log in to Hugging Face
print("Logging in to Hugging Face...")
login()
print("Logging Successful...")

#4.LOAD MODEL AND TOKENIZER
print("Loading model and tokenizer...")
if IS_GPU_ENV:
    # This is the configuration for 4-bit quantization to fit Llama-2 7B in memory.
    # It will only work in a GPU environment.
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
    )
    model = AutoModelForCausalLM.from_pretrained(
        GPU_MODEL_ID,
        quantization_config=bnb_config,
        trust_remote_code=True
    )
    tokenizer = AutoTokenizer.from_pretrained(GPU_MODEL_ID, trust_remote_code=True)
else:
    # For CPU prototyping[load a much smaller model without quantization]
    model = AutoModelForCausalLM.from_pretrained(CPU_MODEL_ID)
    tokenizer = AutoTokenizer.from_pretrained(CPU_MODEL_ID)

tokenizer.pad_token = tokenizer.eos_token
model.config.use_cache = False

# LORA CONFIGURATION
if IS_GPU_ENV:
    print("Applying LoRA configuration to the model...")
    # Prepare the quantized model for LoRA training
    model = prepare_model_for_kbit_training(model)

    # Define the LoRA configuration
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "v_proj"], # Target specific layers for adaptation
        bias="none",
        task_type="CAUSAL_LM"
    )

    # Apply the LoRA adapter to the model
    model = get_peft_model(model, lora_config)
    print("\nLoRA model summary:")
    model.print_trainable_parameters() # Shows how few parameters are being trained

#5. LOAD AND PREPARE THE DATASET
print("Loading and preparing the dataset...")

raw_dataset = load_dataset(DATASET_ID)

# For CPU prototyping- use a small slice of the data.
# For the GPU - use the full dataset.
if IS_GPU_ENV:
    dataset_subset = raw_dataset["train"]
else:
    dataset_subset = raw_dataset["train"].select(range(50))

# Function parses the text to separate the instruction (x) and the output (y).
def parse_instruction_output(example):
    text = example['text']
    parts = text.split("### Assistant:")

    if len(parts) < 2:
        return {"instruction": "", "output": ""}

    instruction = parts[0].replace("### Human:", "").strip()
    output = parts[1].strip()
    return {"instruction": instruction, "output": output}

# Function formats the parsed data for our backward model.
# The goal is to train a model p(x|y), so the input is the output,
def format_for_backward_model(example):
    # The formatted text is what the model will actually see during training.
    return {
        "text": f"### Output:\n{example['output']}\n\n### Instruction:\n{example['instruction']}"
    }

# Apply the functions to the dataset
parsed_dataset = dataset_subset.map(parse_instruction_output)
formatted_dataset = parsed_dataset.map(format_for_backward_model)

# Let's see an example of the final formatted data
print("\n--- Example of final formatted training data ---")
print(formatted_dataset[0]['text'])
print("------------------------------------------------\n")

#6. TOKENIZE THE DATASET
# This step to convert the text into numbers
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, max_length=512)

tokenized_dataset = formatted_dataset.map(tokenize_function, batched=True) # Apply the tokenization to the entire dataset.
# Update the train_dataset in the Trainer to use this new tokenized dataset.
# Also need to remove the columns with raw text, as the trainer expects only tensors.
final_dataset = tokenized_dataset.remove_columns(["instruction", "output", "text"])

#7. SET UP THE TRAINER
print("Setting up the Trainer...")

training_args = TrainingArguments(
    output_dir="backward_model_checkpoints",# The directory where the model checkpoints will be saved.
    num_train_epochs=1,                     # How many times to go through the dataset. One epoch is usually enough for fine-tuning.
    per_device_train_batch_size=2,          # The number of samples per batch on each device
    gradient_accumulation_steps=4,
    report_to="none",
    #bf16=False,                             # For CPU, this should be False.Set to True if using- GPU (like A100)
    fp16=True,
    logging_steps=120,
    logging_dir='./logs',
    run_name="backward-model-lora-finetune", #f"backward-model-cpu-prototype-{_}",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=final_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

#8. TRAIN MODEL
print("Starting LoRA the training process...")
trainer.train()
print("Training complete!")

#9. PUSH THE MODEL TO THE HUB
print(f"Pushing model to the Hugging Face Hub at: {HF_REPO_ID}")
trainer.model.push_to_hub(HF_REPO_ID, commit_message="Pushing model")# Push the model directly from the trainer
tokenizer.push_to_hub(HF_REPO_ID, commit_message="Pushing tokenizer")# Push the tokenizer directly using the main tokenizer variable
print("Model and tokenizer successfully pushed to the Hub!")
print(f"Model URL: https://huggingface.co/{HF_REPO_ID}")

** Finetune model that uses output to predict the instruction **
Found existing installation: cudf-cu12 25.6.0
Uninstalling cudf-cu12-25.6.0:
  Successfully uninstalled cudf-cu12-25.6.0
Found existing installation: pylibcudf-cu12 25.6.0
Uninstalling pylibcudf-cu12-25.6.0:
  Successfully uninstalled pylibcudf-cu12-25.6.0
Found existing installation: dask-cudf-cu12 25.6.0
Uninstalling dask-cudf-cu12-25.6.0:
  Successfully uninstalled dask-cudf-cu12-25.6.0
Found existing installation: cuml-cu12 25.6.0
Uninstalling cuml-cu12-25.6.0:
  Successfully uninstalled cuml-cu12-25.6.0
Logging in to Hugging Face...

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Logging Successful...
Loading model and tokenizer...

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Applying LoRA configuration to the model...

LoRA model summary:
trainable params: 8,388,608 || all params: 6,746,804,224 || trainable%: 0.1243
Loading and preparing the dataset...

README.md:   0%|          | 0.00/395 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

openassistant_best_replies_train.jsonl:   0%|          | 0.00/20.9M [00:00<?, ?B/s]

openassistant_best_replies_eval.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/9846 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/518 [00:00<?, ? examples/s]

Map:   0%|          | 0/9846 [00:00<?, ? examples/s]

Map:   0%|          | 0/9846 [00:00<?, ? examples/s]

--- Example of final formatted training data ---
### Output:
"Monopsony" refers to a market structure where there is only one buyer for a particular good or service. In economics, this term is particularly relevant in the labor market, where a monopsony employer has significant power over the wages and working conditions of their employees. The presence of a monopsony can result in lower wages and reduced employment opportunities for workers, as the employer has little incentive to increase wages or provide better working conditions.

Recent research has identified potential monopsonies in industries such as retail and fast food, where a few large companies control a significant portion of the market (Bivens & Mishel, 2013). In these industries, workers often face low wages, limited benefits, and reduced bargaining power, leading to a situation where they are dependent on the employer for their livelihood. This dependence can result in further suppression of wages and a decline in working conditions.

Overall, the concept of monopsony is essential to understanding the dynamics of labor markets and the impact of market power on workers. Further research is needed to understand the extent and impact of monopsonies on the economy and to develop policies to address this issue.

References:
Bivens, J., & Mishel, L. (2013). The Pay of Corporate Executives and Financial Professionals as Evidence of Rents in Top 1 Percent Incomes. Journal of Economic Perspectives, 27(3), 57-78.### Human: Now explain it to a dog

### Instruction:
Can you write a short introduction about the relevance of the term "monopsony" in economics? Please use examples related to potential monopsonies in the labour market and cite relevant research.
------------------------------------------------

Map:   0%|          | 0/9846 [00:00<?, ? examples/s]

Setting up the Trainer...
Starting LoRA the training process...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Training complete!
Pushing model to the Hugging Face Hub at: dnerkar/llama-2-7b-backward-lora

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   2%|1         |  560kB / 33.6MB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...p0n7bjjp1/tokenizer.model: 100%|##########|  500kB /  500kB

Model and tokenizer successfully pushed to the Hub!
Model URL: https://huggingface.co/dnerkar/llama-2-7b-backward-lora

2. Self-Augmentation

In [2]:
print("** Self-Augmentation **")

#0. Install and Import
print("--Install and Import--")
!pip uninstall -y cudf-cu12 pylibcudf-cu12 dask-cudf-cu12 cuml-cu12
!pip install -q -U transformers datasets accelerate bitsandbytes "numpy==2.0.0" "pyarrow>=15.0.2" peft
from huggingface_hub import login
print("Logging in to Hugging Face...")
login()

#1. SETUP
print("--SetUp--")
import torch
import random
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
# Note: When using LoRA for the GPU version add need:
from peft import PeftModel

# 2. CONFIGURATION
# Set to False to run on CPU with your fine-tuned distilgpt2 | True to run on GPU with the full Llama-2 7B model.
IS_GPU_ENV = True

# Hugging Face Hub repository ID for the backward model
# For the CPU.
CPU_BACKWARD_MODEL_REPO = "dnerkar/llama-2-7b-backward-model-prototype"
# For the GPU version-point to fine-tuned Llama-2 LoRA adapter.
GPU_BACKWARD_LORA_REPO = "dnerkar/llama-2-7b-backward-lora"

# Select the correct repo based on the environment flag.
BACKWARD_MODEL_REPO_ID = GPU_BACKWARD_LORA_REPO if IS_GPU_ENV else CPU_BACKWARD_MODEL_REPO

LIMA_DATASET_ID = "databricks/databricks-dolly-15k"
NUM_SAMPLES = 150 if IS_GPU_ENV else 10

# 3. LOAD THE BACKWARD MODEL
print(f"Loading the backward model from: {BACKWARD_MODEL_REPO_ID}")

if IS_GPU_ENV:
    # section is for when you switch to GPU training.
    # It loads the base Llama-2 model in 4-bit and then attaches your
    # fine-tuned LoRA adapter on top.
    base_model_id = "meta-llama/Llama-2-7b-hf"
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
    )
    base_model = AutoModelForCausalLM.from_pretrained(
        base_model_id,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )
    tokenizer = AutoTokenizer.from_pretrained(base_model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token

    # Load the LoRA adapter on top of the base model.
    model = PeftModel.from_pretrained(base_model, BACKWARD_MODEL_REPO_ID)
    print("Successfully loaded Llama-2 base model with LoRA adapter.")

else:
    # For  CPU prototype -> load the fine-tuned distilgpt2.
    model = AutoModelForCausalLM.from_pretrained(BACKWARD_MODEL_REPO_ID)
    tokenizer = AutoTokenizer.from_pretrained(BACKWARD_MODEL_REPO_ID)
    tokenizer.pad_token = tokenizer.eos_token

model.eval() # Set the model to evaluation mode for generation.

#  4. LOAD AND PROCESS THE LIMA DATASET
print("Loading and processing the Dolly dataset...")

# Load the dataset from the hub
dolly_dataset = load_dataset(LIMA_DATASET_ID, split="train")

#  FIX : The 'databricks-dolly-15k' dataset is already single-turn,
# so no filtering is needed. The completions are in the 'response' column.
completions = dolly_dataset['response']

# Randomly sample the completions
print(f"Randomly sampling {NUM_SAMPLES} completions from {len(completions)} examples.")
sampled_completions = random.sample(list(completions), NUM_SAMPLES)


# 5. GENERATE INSTRUCTIONS
print("\nGenerating new instructions from completions...")
generated_pairs = []
try:
    from tqdm import tqdm
    iterator = tqdm(sampled_completions)
except ImportError:
    iterator = sampled_completions

for completion in iterator:
    prompt = f"### Output:\n{completion}\n\n### Instruction:\n"

    # ## FIX 2 ##: Added .to(model.device) to move input tensors to the same device as the model (GPU or CPU).
    inputs = tokenizer(prompt, return_tensors="pt", max_length=1024, truncation=True).to(model.device)

    output_tokens = model.generate(
        **inputs,
        max_new_tokens=75,
        num_beams=2,
        early_stopping=True,
        no_repeat_ngram_size=2
    )

    full_generated_text = tokenizer.decode(output_tokens[0], skip_special_tokens=True)

    try:
        generated_instruction = full_generated_text.split("### Instruction:")[1].strip()
    except IndexError:
        generated_instruction = "[FAILED TO PARSE INSTRUCTION]"

    generated_pairs.append({
        "generated_instruction": generated_instruction,
        "original_response": completion
    })

print("Instruction generation complete!")


# 6. PRINT 5 EXAMPLES
print("\n--- 5 Examples of Generated (Instruction, Response) Pairs ---")
for i, pair in enumerate(generated_pairs[:5]):
    print(f"\n----- Example {i+1} -----")
    print(f"Generated Instruction: {pair['generated_instruction']}")
    print("-" * 20)
    print(f"Original LIMA Response: {pair['original_response']}")
    print("-" * 25)

** Self-Augmentation **
--Install and Import--
Found existing installation: cudf-cu12 25.6.0
Uninstalling cudf-cu12-25.6.0:
  Successfully uninstalled cudf-cu12-25.6.0
Found existing installation: pylibcudf-cu12 25.6.0
Uninstalling pylibcudf-cu12-25.6.0:
  Successfully uninstalled pylibcudf-cu12-25.6.0
Found existing installation: dask-cudf-cu12 25.6.0
Uninstalling dask-cudf-cu12-25.6.0:
  Successfully uninstalled dask-cudf-cu12-25.6.0
Found existing installation: cuml-cu12 25.6.0
Uninstalling cuml-cu12-25.6.0:
  Successfully uninstalled cuml-cu12-25.6.0
Logging in to Hugging Face...

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

--SetUp--
Loading the backward model from: dnerkar/llama-2-7b-backward-lora

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/859 [00:00<?, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/33.6M [00:00<?, ?B/s]

Successfully loaded Llama-2 base model with LoRA adapter.
Loading and processing the Dolly dataset...

README.md: 0.00B [00:00, ?B/s]

databricks-dolly-15k.jsonl:   0%|          | 0.00/13.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/15011 [00:00<?, ? examples/s]

Randomly sampling 150 completions from 15011 examples.

Generating new instructions from completions...

100%|██████████| 150/150 [18:17<00:00,  7.32s/it]

Instruction generation complete!

--- 5 Examples of Generated (Instruction, Response) Pairs ---

----- Example 1 -----
Generated Instruction: What is the difference between the iPhone 14 and the Apple Watch Ultra?
--------------------
Original LIMA Response: They are exactly the same in terms of technical specifications and capabilities. The only differences between them are their logos and names.
-------------------------

----- Example 2 -----
Generated Instruction: Why can't Jews eat peanut butter during passover?
--------------------
Original LIMA Response: Peanuts are a type of legume. Legumes are banned as they are often mixed with wheat (and Jews typically only eat unleavened bread during Passover).
-------------------------

----- Example 3 -----
Generated Instruction: Why do people like to swim in a pool?
What are the benefits of swimming?  What are some of its drawbacks?
--------------------
Original LIMA Response: Pools are fun because they help to keep people cool when it is hot outside.  Kids love jumping in pool and playing with other kids in the pool too.  Sometimes water slides are connected to pools to offer more fun.  Pools are a great way to relax in the sun, get a tan, or socialize with your friends.  They do have a fair amount of upkeep during the very hot and very cold seasons of the year.  Pools can freeze in the winter and also develop algae in the hot humid weather too.  Chlorine is used to disinfect pools and neutralize in viruses and bacteria.
-------------------------

----- Example 4 -----
Generated Instruction: Which holiday does each of these items belong to? Bunny, Egg, Cobweb, Bucket, Basket, Lights, and Santa.
1. Buny
2. Eater
3. Cobwe
4. Bucke
5. Bask
6. Light
7. Santa
8. None of the above
9
--------------------
Original LIMA Response: Bunny: Easter, egg: Easter, cobwebs: Halloween, candy bucket: Halloween, Candy basket: Easter, lights: Christmas, Santa: Christmas
-------------------------

----- Example 5 -----
Generated Instruction: What is the mascot of Concorde University?
Is it a bird? A dog? An eagle?
--------------------
Original LIMA Response: The Concordia Golden Eagles represent Concordia University Irvine. The Golden Eagles are a member of the Division II level of the National Collegiate Athletic Association (NCAA) and primarily compete in the Pacific West Conference.
-------------------------

3. Self curation

This script will:

Load the meta-llama/Llama-2-7b-chat-hf model using 4-bit quantization.

Construct a detailed prompt using few-shot examples and the instructions from the paper.

Loop through the (instruction, response) pairs you generated in Step 2.

Use the Llama 2 Chat model to assign a quality score (1-5) to each pair.

Filter the pairs into high-quality and low-quality lists.

Print 5 examples from each list.

Push the final high-quality dataset to the Hugging Face Hub.

In [4]:
print("** Self curation **")

# ==============================================================================
# 0. INSTALL LIBRARIES & AUTHENTICATE
# ==============================================================================
!pip uninstall -y cudf-cu12 pylibcudf-cu12 dask-cudf-cu12 cuml-cu12
!pip install -q -U transformers datasets accelerate bitsandbytes "numpy==2.0.0" "pyarrow>=15.0.2" peft

from huggingface_hub import login
print("Logging in to Hugging Face...")
login()

# ==============================================================================
# 1. SETUP - Import Libraries
# ==============================================================================
import torch
import random
import re
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# ==============================================================================
# 2. CONFIGURATION
# ==============================================================================
# Set to True to run the real rating on GPU
IS_GPU_ENV = True

RATING_MODEL_ID = "meta-llama/Llama-2-7b-chat-hf"
CURATED_DATASET_REPO_ID = "dnerkar/self-aligned-curated-dataset"

# This code assumes the 'generated_pairs' list from the previous step is in memory.
if 'generated_pairs' not in globals():
    print("WARNING: 'generated_pairs' not found. Running Step 2 to generate it.")
    # This placeholder is a fallback, but you should have run Step 2 first.
    generated_pairs = [
        {'generated_instruction': 'What are the main ingredients in a margarita?', 'original_response': 'A margarita is a cocktail consisting of tequila, orange liqueur, and lime juice.'},
        {'generated_instruction': 'explain black hole', 'original_response': 'A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape.'},
    ]

# ==============================================================================
# 3. LOAD THE RATING LLM
# ==============================================================================
print("Loading rating model...")

if IS_GPU_ENV:
    print(f"Loading the rating model: {RATING_MODEL_ID} (GPU mode)")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
    )
    rating_model = AutoModelForCausalLM.from_pretrained(
        RATING_MODEL_ID,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )
    rating_tokenizer = AutoTokenizer.from_pretrained(RATING_MODEL_ID, trust_remote_code=True)
    rating_tokenizer.pad_token = rating_tokenizer.eos_token
    rating_model.eval()
else:
    print("CPU mode: Skipping model load. Will generate FAKE ratings for prototyping.")
    rating_model = None
    rating_tokenizer = None

# ==============================================================================
# 4. CONSTRUCT THE CURATION PROMPT
# ==============================================================================

few_shot_prompt = """
[INST]
Here are some examples of how to rate instruction-response pairs.

Example 1:
Instruction: What is the capital of France?
Response: The capital of France is Paris.
Reasoning: This is a perfect, factual, and direct answer to the user's question. It is exactly what an AI assistant should provide.
Score: 5

Example 2:
Instruction: write a python function to add two numbers
Response: you can use the + operator in python, for example, x + y.
Reasoning: The answer is helpful but incomplete. It doesn't provide the full function as requested by the user, only a hint.
Score: 3

Example 3:
Instruction: why is the sky blue?
Response: i like blue. my favorite color is blue. blue is the best.
Reasoning: The response is off-topic and does not answer the user's question at all. It seems to be a random personal opinion.
Score: 1
[/INST]
"""

paper_prompt_template = """
[INST]
Below is an instruction from a user and a candidate answer. Evaluate whether or not the answer is a good example of how an AI Assistant should respond to the user's instruction. Please assign a score using the following 5-point scale:
1: It means the answer is incomplete, vague, off-topic, controversial, or not exactly what the user asked for. For example, some content seems missing, a numbered list does not start from the beginning, or the opening sentence repeats the user's question. Or the response is from another person's perspective with their personal experience (e.g., taken from blog posts), or looks like an answer from a forum. Or it contains promotional text, navigation text, or other irrelevant information.
2: It means the answer addresses most of the asks from the user. It does not directly address the user's question. For example, it only provides a high-level methodology instead of the exact solution to the user's question.
3: It means the answer is helpful but not written by an AI Assistant. It addresses all the basic asks from the user. It is complete and self-contained with the drawback that the response is not written from an AI assistant's perspective, but from other people's perspective. For example, it contains personal experience or opinion, or mentions a comments section.
4: It means the answer is written from an AI assistant's perspective with a clear focus on addressing the. It provides a complete, clear, and comprehensive response to the user's question or instruction without missing or irrelevant information. It is well organized, self-contained, and written in a helpful tone. It has minor room for improvement, e.g., being more concise.
5: It means it is a perfect answer from an AI Assistant. It has a clear focus on being a helpful AI Assistant, where the response looks like it was intentionally written to address the user's question or instruction without any irrelevant sentences. The answer provides high-quality content, demonstrating expert knowledge in the area, is very well written, logical, easy-to-follow, engaging, and insightful.

Please first provide a brief reasoning you used to derive the rating score, and then write "Score: <rating>" in the last line.

Instruction: {instruction}
Response: {response}
[/INST]
"""

def create_rating_prompt(instruction, response):
    return few_shot_prompt + paper_prompt_template.format(instruction=instruction, response=response)

# ==============================================================================
# 5. RATE THE GENERATED PAIRS
# ==============================================================================
print(f"Rating {len(generated_pairs)} generated pairs... (This may take a while)")

rated_pairs = []
try:
    from tqdm import tqdm
    iterator = tqdm(generated_pairs)
except ImportError:
    iterator = generated_pairs

for pair in iterator:
    # ## THIS IS THE CORRECTED LOGIC BLOCK ##
    if IS_GPU_ENV:
        # --- This is the GPU Path ---
        prompt = create_rating_prompt(pair['generated_instruction'], pair['original_response'])
        inputs = rating_tokenizer(prompt, return_tensors="pt").to("cuda")

        # Get the length of your input prompt
        input_token_length = inputs.input_ids.shape[1]

        output_tokens = rating_model.generate(
            **inputs,
            max_new_tokens=100,
            do_sample=False
        )

        # Get ONLY the new tokens by slicing
        new_tokens = output_tokens[0][input_token_length:]

        # Decode only the new tokens
        rating_output = rating_tokenizer.decode(new_tokens, skip_special_tokens=True)

        match = re.search(r"Score:\s*(\d)", rating_output)
        if match:
            score = int(match.group(1))
        else:
            score = 0 # Assign a low score if parsing fails
    else:
        # --- This is the CPU Path ---
        score = random.choice([1, 3, 5]) # Assign a random score for testing

    pair['score'] = score
    rated_pairs.append(pair)

print("Rating complete!")

# ==============================================================================
# 6. CURATE DATASET AND PRINT EXAMPLES
# ==============================================================================
high_quality = [p for p in rated_pairs if p['score'] >= 4]
low_quality = [p for p in rated_pairs if p['score'] < 4]

print(f"\nFound {len(high_quality)} high-quality examples and {len(low_quality)} low-quality examples.")

print("\n--- 5 High-Quality Examples ---")
for i, pair in enumerate(high_quality[:5]):
    print(f"\n----- HQ Example {i+1} (Score: {pair['score']}) -----")
    print(f"Instruction: {pair['generated_instruction']}")
    print(f"Response: {pair['original_response']}")

print("\n\n--- 5 Low-Quality Examples ---")
for i, pair in enumerate(low_quality[:5]):
    print(f"\n----- LQ Example {i+1} (Score: {pair['score']}) -----")
    print(f"Instruction: {pair['generated_instruction']}")
    print(f"Response: {pair['original_response']}")

# ==============================================================================
# 7. PUSH CURATED DATASET TO HUB
# ==============================================================================
if high_quality:
    print(f"\nPushing {len(high_quality)} high-quality examples to the Hub...")
    high_quality_dataset = Dataset.from_list(high_quality)
    high_quality_dataset.push_to_hub(CURATED_DATASET_REPO_ID)

    print("Dataset successfully pushed to the Hub!")
    print(f"Dataset URL: https://huggingface.co/datasets/{CURATED_DATASET_REPO_ID}")
else:
    print("\nNo high-quality examples found to push to the Hub.")

** Self curation **
WARNING: Skipping cudf-cu12 as it is not installed.
WARNING: Skipping pylibcudf-cu12 as it is not installed.
WARNING: Skipping dask-cudf-cu12 as it is not installed.
WARNING: Skipping cuml-cu12 as it is not installed.
Logging in to Hugging Face...

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Loading rating model...
Loading the rating model: meta-llama/Llama-2-7b-chat-hf (GPU mode)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Rating 150 generated pairs... (This may take a while)

100%|██████████| 150/150 [13:29<00:00,  5.40s/it]

Rating complete!

Found 93 high-quality examples and 57 low-quality examples.

--- 5 High-Quality Examples ---

----- HQ Example 1 (Score: 5) -----
Instruction: Why can't Jews eat peanut butter during passover?
Response: Peanuts are a type of legume. Legumes are banned as they are often mixed with wheat (and Jews typically only eat unleavened bread during Passover).

----- HQ Example 2 (Score: 5) -----
Instruction: Which holiday does each of these items belong to? Bunny, Egg, Cobweb, Bucket, Basket, Lights, and Santa.
1. Buny
2. Eater
3. Cobwe
4. Bucke
5. Bask
6. Light
7. Santa
8. None of the above
9
Response: Bunny: Easter, egg: Easter, cobwebs: Halloween, candy bucket: Halloween, Candy basket: Easter, lights: Christmas, Santa: Christmas

----- HQ Example 3 (Score: 5) -----
Instruction: What is the mascot of Concorde University?
Is it a bird? A dog? An eagle?
Response: The Concordia Golden Eagles represent Concordia University Irvine. The Golden Eagles are a member of the Division II level of the National Collegiate Athletic Association (NCAA) and primarily compete in the Pacific West Conference.

----- HQ Example 4 (Score: 4) -----
Instruction: Who was Swiss bank corporation? What happened to it?
What was its logo?
Response: The Swiss Bank Corporation was a Swiss investment bank and financial services company located in Switzerland. Prior to its merger, the bank was the third largest in Switzerland with over CHF 300 billion of assets and CHF 11.7 billion of equity.

Throughout the 1990s, SBC engaged in a large growth initiative, shifting its focus from traditional commercial banking into investment banking, in an effort to match its larger Swiss rival Credit Suisse. As part of this strategy, SBC acquired US-based investment bank Dillon Read & Co. as well as London-based merchant bank S.G. Warburg in the mid-1990s. SBC also acquired Chicago-based Brinson Partners and O'Connor & Associates. These acquisitions formed the basis for a global investment banking business.

In 1998, SBC merged with Union Bank of Switzerland to form UBS, the largest bank in Europe and the second largest bank in the world. The company's logo, which featured three keys, symbolizing "confidence, security, and discretion", was adopted by UBS after the 1998 merger. Although the combination of the two banks was billed as a merger of equals, it quickly became evident that from a management perspective, it was SBC that was buying UBS as nearly 80% of the top management positions were filled by legacy Swiss Bank professionals. Today, what was SBC forms the core of many of UBS's businesses, particularly UBS Investment Bank.

----- HQ Example 5 (Score: 4) -----
Instruction: What is the name of the movie "The Marchese of Armani" and who is in the cast?
Response: The Marquise of Armiani (German: Die Marchesa d'Armiani) is a 1920 German silent film directed by Alfred Halm and starring Pola Negri, Ernst Dernburg, and Elsa Wagner.

The film's sets were designed by the art director Kurt Richter.

Cast
Pola Negri as Marchesa Assunta
Ernst Dernburg as Polizeichef
Elsa Wagner as Assuntas Mutter
Max Pohl
Fritz Schulz


--- 5 Low-Quality Examples ---

----- LQ Example 1 (Score: 1) -----
Instruction: What is the difference between the iPhone 14 and the Apple Watch Ultra?
Response: They are exactly the same in terms of technical specifications and capabilities. The only differences between them are their logos and names.

----- LQ Example 2 (Score: 0) -----
Instruction: Why do people like to swim in a pool?
What are the benefits of swimming?  What are some of its drawbacks?
Response: Pools are fun because they help to keep people cool when it is hot outside.  Kids love jumping in pool and playing with other kids in the pool too.  Sometimes water slides are connected to pools to offer more fun.  Pools are a great way to relax in the sun, get a tan, or socialize with your friends.  They do have a fair amount of upkeep during the very hot and very cold seasons of the year.  Pools can freeze in the winter and also develop algae in the hot humid weather too.  Chlorine is used to disinfect pools and neutralize in viruses and bacteria.

----- LQ Example 3 (Score: 3) -----
Instruction: Which of these smells smell the best?
1. Candle
2. Pig
3. Skunk
4. Poop
5. Febreaze
6. Incense
Write them in order from best to worst.
If you don't know the answer, guess.
Response: Candle: Smells Good
Pig: Smells Bad
Skunk: Smells Bad
Poop: Smells Bad
Febreze: Smells Good
Incense: Smells Good

----- LQ Example 4 (Score: 2) -----
Instruction: What are the 3 cannels in putla chervu?
Which one is for water supply and which are for sewerage?
Response: There are three canals in Putlacheruvu. One is used for drinking water and the other two are sewage canals used for pumping water into the fish tanks.

----- LQ Example 5 (Score: 2) -----
Instruction: Why do companies pre announce their products?
What are the benefits and drawbacks?
Response: Companies pre-announce their future products because of the following reasons:
1. to reassure current customers that their product is improving
2. to comfort current customers that a lower cost model of their is coming
2. to increase the interest of the media and investors in the company's future prospects
3. to intimidate or confuse competitors

Pushing 93 high-quality examples to the Hub...

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 33.7kB / 33.7kB

README.md:   0%|          | 0.00/363 [00:00<?, ?B/s]

Dataset successfully pushed to the Hub!
Dataset URL: https://huggingface.co/datasets/dnerkar/self-aligned-curated-dataset

Finetune base model on dataset generated in step 3

In [4]:
print("** Finetune base model on dataset generated in step 3 **")
# 0. INSTALL LIBRARIES & AUTHENTICATE
!pip install -q -U transformers datasets accelerate bitsandbytes "numpy==2.0.0" "pyarrow>=15.0.2" peft

** Finetune base model on dataset generated in step 3 **

In [6]:
from huggingface_hub import login
print("Logging in to Hugging Face...")
login()

Logging in to Hugging Face...

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
#1. SETUP - Import Libraries
import torch
from datasets import Dataset, load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [10]:
# ==============================================================================
# 2. CONFIGURATION - Set key variables
# ==============================================================================
IS_GPU_ENV = True
CPU_BASE_MODEL_ID = "distilgpt2"
GPU_BASE_MODEL_ID = "meta-llama/Llama-2-7b-hf"
CURATED_DATASET_REPO_ID = "dnerkar/self-aligned-curated-dataset"
FINAL_MODEL_REPO_ID = "dnerkar/llama-2-7b-self-aligned-model"

In [11]:
# ==============================================================================
# 3. LOAD THE CURATED DATASET
# ==============================================================================
print("Loading the curated dataset...")
if IS_GPU_ENV:
    curated_dataset = load_dataset(CURATED_DATASET_REPO_ID, split="train")
else:
    # ... (CPU placeholder code) ...
    print("CPU mode: Creating a placeholder for the curated dataset.")
    placeholder_data = [
        {'generated_instruction': 'What is the capital of France?', 'original_response': 'The capital of France is Paris.', 'score': 5},
        {'generated_instruction': 'Explain the theory of relativity...', 'original_response': '...', 'score': 4}
    ]
    curated_dataset = Dataset.from_list(placeholder_data)

Loading the curated dataset...

In [12]:
# 4. LOAD BASE MODEL AND TOKENIZER
print("Loading base model and tokenizer...")

if IS_GPU_ENV:
    print(f"GPU mode: Loading {GPU_BASE_MODEL_ID} with 4-bit quantization...")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )
    model = AutoModelForCausalLM.from_pretrained(
        GPU_BASE_MODEL_ID,
        quantization_config=bnb_config,
        # Changed "auto" to {"": 0} to force model onto the GPU.
        device_map={"": 0},
        trust_remote_code=True
    )
    tokenizer = AutoTokenizer.from_pretrained(GPU_BASE_MODEL_ID, trust_remote_code=True)
else:
    # ... (CPU model loading code) ...
    print(f"CPU mode: Loading {CPU_BASE_MODEL_ID}...")
    model = AutoModelForCausalLM.from_pretrained(CPU_BASE_MODEL_ID)
    tokenizer = AutoTokenizer.from_pretrained(CPU_BASE_MODEL_ID)

tokenizer.pad_token = tokenizer.eos_token
model.config.use_cache = False

Loading base model and tokenizer...
GPU mode: Loading meta-llama/Llama-2-7b-hf with 4-bit quantization...

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [13]:
# 5. PREPARE AND TOKENIZE THE DATA
print("Formatting and tokenizing the dataset...")
def format_for_finetuning(example):
    return {
        "text": f"### Human:\n{example['generated_instruction']}\n\n### Assistant:\n{example['original_response']}"
    }

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, max_length=512)

formatted_dataset = curated_dataset.map(format_for_finetuning)
tokenized_dataset = formatted_dataset.map(tokenize_function, batched=True)
final_train_dataset = tokenized_dataset.remove_columns(curated_dataset.column_names)

# 6. CONFIGURE LORA (for GPU) AND TRAINER
if IS_GPU_ENV:
    print("GPU mode: Preparing model for LoRA training...")
    model = prepare_model_for_kbit_training(model)
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        target_modules=["q_proj", "v_proj"],
        bias="none",
        task_type="CAUSAL_LM"
    )
    model = get_peft_model(model, lora_config)

print("Setting up Training Arguments...")
training_args = TrainingArguments(
    output_dir="final_model_checkpoints",
    num_train_epochs=50, # Increased epochs
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    # ## FIX 2 ##: Changed logging steps to see progress more often.
    logging_steps=10,
    report_to="none",
    fp16=True if IS_GPU_ENV else False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=final_train_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

# 7. TRAIN THE FINAL MODEL
print("Starting final model fine-tuning...")
trainer.train()
print("Fine-tuning complete!")

# 8. PRINT 5 EXAMPLE RESPONSES
print("\n--- Generating 5 Example Responses ---")
example_prompts = [
    "What is the most populous country in the world?",
    "Write a short, happy poem about a cat.",
    "Explain the difference between a list and a tuple in Python.",
    "What are three tips for staying healthy?",
    "Who wrote the play 'Hamlet'?"
]

for prompt_text in example_prompts:
    prompt = f"### Human:\n{prompt_text}\n\n### Assistant:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    output_tokens = model.generate(**inputs,
                                     max_new_tokens=100,
                                     do_sample=True,
                                     temperature=0.7,
                                     top_p=0.9)
    response = tokenizer.decode(output_tokens[0], skip_special_tokens=True)

    try:
        response_text = response.split("### Assistant:\n")[1].strip()
    except IndexError:
        response_text = "Failed to generate a valid response."

    print(f"\n----- Prompt: {prompt_text} -----")
    print(response_text)
    print("=" * 30)

# 9. PUSH THE FINAL MODEL TO THE HUB
print(f"\nPushing the final model to the Hub at: {FINAL_MODEL_REPO_ID}")

trainer.model.push_to_hub(FINAL_MODEL_REPO_ID, commit_message="Pushing final LoRA model")
tokenizer.push_to_hub(FINAL_MODEL_REPO_ID, commit_message="Pushing tokenizer")

print("Final model and tokenizer successfully pushed!")
print(f"Model URL: https://huggingface.co/{FINAL_MODEL_REPO_ID}")

Formatting and tokenizing the dataset...

Map:   0%|          | 0/93 [00:00<?, ? examples/s]

Map:   0%|          | 0/93 [00:00<?, ? examples/s]

GPU mode: Preparing model for LoRA training...
Setting up Training Arguments...
Starting final model fine-tuning...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Caching is incompatible with gradient checkpointing in LlamaDecoderLayer. Setting `past_key_values=None`.

Fine-tuning complete!

--- Generating 5 Example Responses ---

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

----- Prompt: What is the most populous country in the world? -----
Acc ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
==============================

----- Prompt: Write a short, happy poem about a cat. -----
There ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
==============================

----- Prompt: Explain the difference between a list and a tuple in Python. -----
A ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
==============================

----- Prompt: What are three tips for staying healthy? -----
1 ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
==============================

----- Prompt: Who wrote the play 'Hamlet'? -----
The ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
==============================

Pushing the final model to the Hub at: dnerkar/llama-2-7b-self-aligned-model

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   2%|1         |  560kB / 33.6MB

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...p48nmyj0s/tokenizer.model: 100%|##########|  500kB /  500kB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Final model and tokenizer successfully pushed!
Model URL: https://huggingface.co/dnerkar/llama-2-7b-self-aligned-model